version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_book
    environment:
      MYSQL_DATABASE: webbansach
      MYSQL_ROOT_PASSWORD: 2904
    ports:
      - "3308:3306"
    expose:
      - 3308
    volumes:
      - db:/var/lib/mysql
    networks:
      - webbansach
  redis:
    image: redis:latest
    container_name: redis_book
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: 2904
      REDIS_PORT: 6379
      REDIS_DATABASE: 16
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes --requirepass 2904 # Đặt mật khẩu cho Redis và bật tính năng ghi dữ liệu
    networks:
      - webbansach
#  webbansach:
#    image: webbansach
#    container_name: webbansach
#    ports:
#      - 8081:8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/webbansach
#      SPRING_DATASOURCE_USERNAME: ducbao
#      SPRING_DATASOURCE_PASSWORD: 2904
#    depends_on:
#      - mysql
#      - redis
#    networks:
#      - webbansach
  #elasticsearch
  elasticsearch:
    container_name: elasticsearch-container
    restart: always
    image: elasticsearch:8.14.3
    ports:
      - 9200:9200
    environment:
#      #sử dụng cho một cụm 1 node
#      - "discovery:type=single-node"
#      # Cài đặt này được sử dụng để vô hiệu hóa các tính năng bảo mật của X-Pack trong Elasticsearch.
#      -  "xpack.security.enabled=false"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - webbansach
  kibana:
    container_name: kibana-container
    image: kibana:8.14.3
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - webbansach
networks:
  webbansach:
    driver: bridge
volumes:
  db:
  redis-data: